sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t andrevargas/multi-container-aws-client -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true andrevargas/multi-container-aws-client yarn test

after_success:
  - docker build -t andrevargas/multi-container-aws-api ./api
  - docker build -t andrevargas/multi-container-aws-nginx ./nginx
  - docker build -t andrevargas/multi-container-aws-client ./client
  - docker build -t andrevargas/multi-container-aws-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to the registry
  - docker push andrevargas/multi-container-aws-api
  - docker push andrevargas/multi-container-aws-nginx
  - docker push andrevargas/multi-container-aws-client
  - docker push andrevargas/multi-container-aws-worker

deploy:
  edge: true
  on:
    branch: master
  provider: elasticbeanstalk
  app: multi-container-aws
  env: MultiContainerAws-env
  region: us-east-1
  bucket_name: elasticbeanstalk-us-east-1-609982889420
  bucket_path: multi-container-aws
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  