version: '3.7'

services:
  redis:
    image: redis:latest
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3050:80
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: postgres
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - ./worker/app
      - /app/node_modules
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379